version: 2
jobs:
  test:
    docker:
    - image: circleci/node:10.15.2-stretch-browsers
    steps:
    - checkout
    - run:
        name: Update npm
        command: 'sudo npm install -g npm@6.4.1'
    - run:
        name: Install npm dependencies
        command: 'npm install'
    - run:
        name: rebuild modules
        command: npm rebuild
    - run:
        name: Lint
        command: npm run lint
workflows:
  version: 2
  test_and_deploy:
    jobs:
    - test
